### ISSUE TITLE
Error due to job_extra_directives

### ISSUE THREAD

**Issue by geonmo** [cernops/dask-lxplus#8]
Hello, dask-lxplus developer teams.

I faced some errors due to "job_extra_directives".

I guess that the "job_extra_directives" is disappeared on current dask_jobqueue.

Here is an error log.

```bash
======================================================================
ERROR: test_job_script_docker (__main__.TestCluster)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos9-gcc11-opt/lib/python3.9/site-packages/dask_jobqueue/core.py", line 558, in _dummy_job
    return self.job_cls(
  File "/afs/cern.ch/user/g/geonmo/.local/lib/python3.9/site-packages/dask_lxplus/cluster.py", line 86, in __init__
    super().__init__(scheduler=scheduler, name=name, disk=disk, **base_class_kwargs)
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos9-gcc11-opt/lib/python3.9/site-packages/dask_jobqueue/htcondor.py", line 45, in __init__
    super().__init__(
TypeError: __init__() got an unexpected keyword argument 'job_extra_directives'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/afs/cern.ch/user/g/geonmo/dask/test_cluster.py", line 53, in test_job_script_docker
    with CernCluster(
  File "/afs/cern.ch/user/g/geonmo/.local/lib/python3.9/site-packages/dask_lxplus/cluster.py", line 168, in __init__
    super().__init__(**base_class_kwargs)
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos9-gcc11-opt/lib/python3.9/site-packages/dask_jobqueue/core.py", line 529, in __init__
    self._dummy_job  # trigger property to ensure that the job is valid
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos9-gcc11-opt/lib/python3.9/site-packages/dask_jobqueue/core.py", line 576, in _dummy_job
    raise ValueError(
ValueError: Got unexpected keyword argument 'job_extra_directives'. Very likely this unexpected parameter was passed in "job_kwargs" in the CernCluster constructor:
job_kwargs={'cores': 4, 'processes': 2, 'memory': '2000MB', 'disk': '1000MB', 'job_extra_directives': {'transfer_output_files': '""', 'JobBatchName': '"dask-worker"', 'MY.Jobflavour': '"longlunch"', 'MY.IsDaskWorker': 'true', 'docker_image': '"dask-lxplus/lxdask-cc7:latest"', 'universe': 'docker'}, 'submit_command_extra': ['-spool'], 'worker_extra_args': ['--worker-port', '10000:10100'], 'config_name': 'cern', 'interface': None, 'protocol': 'tcp://', 'security': None}

```

**Comment by bendylan** [comment]
It's actually the other way around, the version of dask in LCG_102 didn't support the newer job_extra_directives. I've fixed the readme to suggest a newer lcg release.
